Repository WalletConnect/verify-server, pull requests merged in 2023-05, with the labels that each got.

#27 feat: Temporary disable Content-Security-Policy
  Cargo.lock
  integration/integration.test.ts
  src/http_server/mod.rs
Labels: enhancement

#28 fix: don't post /attestation if attestationId is invalid
  Cargo.lock
  src/http_server/index_js.rs
Labels: bug

#29 feat(infra): downsize redis
  terraform/main.tf
Labels: accepted
